# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 20:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testsforall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Imagen de soporte.', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de creaci\xf3n')),
                ('last_edition', models.DateTimeField(help_text='\xdaltima edici\xf3n', null=True)),
                ('future_publication', models.DateTimeField(help_text='Fecha de publicacion', null=True)),
                ('future_close', models.DateTimeField(help_text='Fecha de cierre', null=True)),
                ('published', models.BooleanField(default=False, help_text='Publicado')),
                ('typesurvey', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 5, 20, 20, 35, 56, 641632), help_text='Fecha de creacion')),
                ('role', models.IntegerField(default=2)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('hashlink', models.CharField(default=testsforall.models._createHash, max_length=10, unique=True)),
                ('user', models.ForeignKey(help_text='UserTest', on_delete=django.db.models.deletion.CASCADE, related_name='UserTest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('survey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Survey')),
            ],
            bases=('testsforall.survey',),
        ),
        migrations.CreateModel(
            name='Multiple',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Question')),
                ('nok', models.IntegerField()),
            ],
            bases=('testsforall.question',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('survey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Survey')),
                ('rules', models.CharField(max_length=500, null=True)),
            ],
            bases=('testsforall.survey',),
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='User', to='testsforall.UserTests'),
        ),
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.ManyToManyField(blank=True, help_text='Imagen', to='testsforall.Image'),
        ),
        migrations.AddField(
            model_name='survey',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Participantes', to='testsforall.UserTests'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ForeignKey(help_text='Imagen de soporte.', null=True, on_delete=django.db.models.deletion.CASCADE, to='testsforall.Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(help_text='Test', on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='testsforall.Survey'),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(help_text='Uploader', on_delete=django.db.models.deletion.CASCADE, related_name='Uploader', to='testsforall.UserTests'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(help_text='Lider', on_delete=django.db.models.deletion.CASCADE, related_name='Lider', to='testsforall.UserTests'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(help_text='Miembros', to='testsforall.UserTests'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ForeignKey(help_text='Imagen de respuesta.', null=True, on_delete=django.db.models.deletion.CASCADE, to='testsforall.Image'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='testsforall.Question'),
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Test')),
                ('limitwrong', models.IntegerField()),
            ],
            bases=('testsforall.test',),
        ),
        migrations.CreateModel(
            name='MultipleWrongMinus',
            fields=[
                ('multiple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Multiple')),
                ('discount', models.FloatField()),
            ],
            bases=('testsforall.multiple',),
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Test')),
            ],
            bases=('testsforall.test',),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('encuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Encuesta')),
            ],
            bases=('testsforall.encuesta',),
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('encuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testsforall.Encuesta')),
            ],
            bases=('testsforall.encuesta',),
        ),
    ]
