# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsforall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='editors',
            field=models.ManyToManyField(help_text='Editores', related_name='editors', to='testsforall.UserTests'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Participantes', related_name='participants', to='testsforall.UserTests'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 14, 11, 22, 613475), help_text='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='results',
            name='survey',
            field=models.ForeignKey(help_text='Survey realizada', on_delete=django.db.models.deletion.CASCADE, to='testsforall.Survey'),
        ),
        migrations.AddField(
            model_name='results',
            name='user',
            field=models.ForeignKey(help_text='Usuario que ha hecho el test', on_delete=django.db.models.deletion.CASCADE, to='testsforall.UserTests'),
        ),
    ]
