# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsforall', '0002_auto_20170522_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daterequest', models.DateTimeField(default=datetime.datetime(2017, 5, 22, 14, 18, 0, 912715), help_text='Fecha de solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='usertests',
            name='friends',
            field=models.ManyToManyField(help_text='Friends', related_name='_usertests_friends_+', to='testsforall.UserTests'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 14, 18, 0, 908966), help_text='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='petitioner',
            field=models.ForeignKey(help_text='Solicitante de amistad', on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='testsforall.UserTests'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requested',
            field=models.ForeignKey(help_text='Solicitado de amistad', on_delete=django.db.models.deletion.CASCADE, related_name='solicitado', to='testsforall.UserTests'),
        ),
    ]
