# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsforall', '0004_auto_20170522_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='daterequest',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 17, 17, 18, 404229), help_text='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 17, 17, 18, 401977), help_text='Fecha de creacion'),
        ),
    ]
