# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsforall', '0006_auto_20170522_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de creaci\xf3n'),
        ),
        migrations.AddField(
            model_name='group',
            name='last_edition',
            field=models.DateTimeField(help_text='\xdaltima edici\xf3n', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='daterequest',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 22, 22, 51, 306681), help_text='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 22, 22, 51, 304640), help_text='Fecha de creacion'),
        ),
    ]
