# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsforall', '0007_auto_20170522_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='max_result',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='daterequest',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 14, 49, 45, 633662), help_text='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 14, 49, 45, 631590), help_text='Fecha de creacion'),
        ),
    ]
