# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsforall', '0008_auto_20170523_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='daterequest',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 14, 56, 59, 146709), help_text='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 14, 56, 59, 144259), help_text='Fecha de creacion'),
        ),
    ]
