# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsforall', '0011_auto_20170523_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valueminus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='datedone',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 21, 37, 38, 637882), help_text='Fecha de realizaci\xf3n de test'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='daterequest',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 21, 37, 38, 622092), help_text='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_result',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 21, 37, 38, 620031), help_text='Fecha de creacion'),
        ),
    ]
